#!/bin/bash

set -e

if [[ -e /etc/profile ]]; then
	source /etc/profile
fi

# some platforms don't have a realpath binary
cwd=$(perl -e 'use Cwd "abs_path";print abs_path(shift)' $0/..)

CLASSPATH="$(echo ${cwd}/target/camus-*-SNAPSHOT-shaded.jar):$(hadoop classpath)"
/usr/bin/java -cp $CLASSPATH com.linkedin.camus.etl.kafka.CamusJob "$@"

for opt in $@
do
  if [[ $opt == *"camus.job.name"* ]]; then
    job_name=${opt#*=}
    cat <<EOF | curl --data-binary @- http://prometheus.remerge.io:9091/metrics/job/pushgateway
      # TYPE camus_run_timestamp gauge
      # HELP Last successful run timestamp of camus.
      camus_run_timestamp{instance="$(HOSTNAME)",camus_job_name="${job_name}"} $(date +%s)
EOF
    break
  fi
done
